
 - hosts: all
   become: yes 
   tasks:

    - name: Run a script on the remote node
      ansible.builtin.script: ~/Cluster/k8s.project/script.sh --install docker
      args:
        creates: /etc/apt/keyrings/docker.asc

